### ISSUE TITLE
Missing disclaimer in "Useless websites" section

### ISSUE THREAD

**Issue by N3LX** [sefinek24/PiHole-Blocklist-Collection#1]
Please add a disclaimer on [Useless websites](https://github.com/sefinek24/PiHole-Blocklist-Collection/blob/main/info/block/Useless%20websites.md) that the sites included in this list were placed here only based on some kind of prejudice against (mainly polish) LGBT community or provide a criteria which you have used to deem such sites useless.

The file in question is https://cdn.sefinek.net/resources/PiHole-Blocklist-Collection/blocklist/useless-websites.txt and currently looks like this.

![image](https://user-images.githubusercontent.com/58139050/232507526-77d40e5d-c12f-4534-946f-e447bd242b3d.png)

**Comment by sefinek24** [comment]
Thanks, added in #3e20fc55ae5494d20be696c55e50657d87d33d38
